spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    schemas: PUBLIC
app:
  envName: test
logging:
  level:
    htnk128.kotlin.spring.boot.ddd.sample: DEBUG
    Exposed: DEBUG
