@startuml

actor User

:ユーザ: as User
(アカウントを取得) as (find)
(アカウントをすべて取得) as (findAll)
(アカウントを作成) as (Create)
(アカウントを更新) as (Update)
(アカウントを削除) as (Delete)

User --> (find)
User --> (findAll)
User --> (Create)
User --> (Update)
User --> (Delete)

@enduml
