on:
  push:
    branches-ignore:
      - master

name: check_build

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java runtime
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'

#      - name: KtlintCheck
#        env:
#          TZ: Asia/Tokyo
#        run: ./gradlew ktlintCheck

      - name: Build
        env:
          TZ: Asia/Tokyo
        run: ./gradlew build

  check_build:
    name: check_build
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Finish
        run: echo "done"
